### ISSUE TITLE
Authentication constants aren't public and not exposed

### ISSUE THREAD

**Issue by own2pwn** [sbertix/Swiftchain#6]
https://github.com/sbertix/Swiftchain/blob/dff136ab54df5768c1b8a234bc7c6fd212b280f7/Sources/Swiftchain/KeychainAuthentication.swift#L34

**Comment by sbertix** [comment]
Thanks for pointing this out @own2pwn 💪 
Big oversight on my part. I'm gonna fix it by the end of the day.
